config/routes.rb
Rails.application.routes.draw do
  root 'books#index'
  resources :books
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :fetch_book, only: %i[show edit update destroy]

  def index
    @books = Book.all
  end

  def show; end

  def edit; end

  def update
    return redirect_to @book if @book.update(book_params)
    
	  render :edit
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)

    return  redirect_to @book if @book.save
    
    render :new
  end

  def destroy
    @book.destroy
    redirect_to books_url, status: :see_other
  end

private

  def book_params
    params.require(:book).
      permit(:name, :origin, :pages, :publication_date, :description, :author)
  end

  def fetch_book
    @book = Book.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
  def pages(book)
    if book == 0
      "Blank"
    else
      number_with_precision(book.pages, precision: 0)
    end
  end

  def day_and_time(book)
    book.publication_date.strftime("%Y")
  end
end

app/views/books/_book.html.erb
<% @books.each do |book| %>
  <section class="book">
    <div class="summary">
      <h2><%= link_to book.name, book %></h2>
    <p>  Publication Date: <%= day_and_time(book) %> </p> 
    <p> Origin: <%= book.origin %></p>
      <span class="pages">
      pages:  <%= pages(book) %>
      </span>
      <p>
        <%= truncate(book.description, length: 35, separator: ' ') %>
      </p>
    </div>
  </section>
<% end %>

app/views/books/_form.html.erb
<%= form_with(model: book) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, autofocus: true %>

  <%= f.label :description %>
  <%= f.text_area :description, rows: 5 %>

  <%= f.label :origin %>
  <%= f.text_field :origin %>

  <%= f.label :pages %>
  <%= f.number_field :pages %>

  <%= f.label :publication_date %>
  <%= f.datetime_select :publication_date, {ampm: true}, {class: "datetime"} %>

  <%= f.label :author %>
  <%= f.text_field :author, autofocus: true %>

  <%= f.submit %>
<% end %>

app/views/books/edit.html.erb
<h1>Editing <%= @book.name %></h1>

<%= render "form", book: @book %>

app/views/books/index.html.erb
<%= render "book", book: @book %>

<section class="admin">
  <%= link_to "Add New Book", new_book_path, class: "button" %>
</section>

app/views/books/new.html.erb
<h1>Create a New Book</h1>

<%= render "form", book: @book %>

app/views/books/show.html.erb
<section class="book-details">
  <div class="details">
    <h1><%= @book.name %></h1>
    <p>
      <%= pages(@book) %> pages
    </p>
    <p> Publication Date:
      <%= day_and_time(@book) %>
    </p>
    <p>
      <%= @book.description %>
    </p>
    <p>
     Origin: <%= @book.origin %>
    </p>
    <p>
     Author: <%= @book.author %>
    </p>
  </div>
</section>

<section class="admin">
  <%= link_to "Edit", edit_book_path(@book), class: "button" %>
  <%= link_to "Delete", @book, class: "button",
        data: { turbo_method: :delete, turbo_confirm: "Really?!" } %>
</section>

app/views/layouts/_footer.html.erb
<footer>
  <p>
    Made with Love</a>
  </p>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav>
    <%= link_to "Book", root_path %>
    <ul>
      <li>
        <%= link_to "All Books", books_path %>
      </li>
    </ul>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Boox</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="stylesheet" href="https://cdn.simplecss.org/simple.min.css">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>

    <%= render "layouts/header" %>

    <div class="content">
      <%= yield %>
    </div>

    <%= render "layouts/footer" %>

  </body>
</html>